// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HillarysHair.Migrations
{
    [DbContext(typeof(HillarysHairDbContext))]
    partial class HillarysHairDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HillarysHair.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StylistId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StylistId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            ScheduledAt = new DateTime(2026, 6, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            StylistId = 1,
                            TotalCost = 55.00m
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            ScheduledAt = new DateTime(2026, 6, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            StylistId = 2,
                            TotalCost = 110.00m
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 3,
                            ScheduledAt = new DateTime(2026, 6, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            StylistId = 1,
                            TotalCost = 65.00m
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 4,
                            ScheduledAt = new DateTime(2026, 6, 11, 11, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            StylistId = 3,
                            TotalCost = 35.00m
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 5,
                            ScheduledAt = new DateTime(2026, 6, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Cancelled",
                            StylistId = 2,
                            TotalCost = 110.00m
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 6,
                            ScheduledAt = new DateTime(2026, 6, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            StylistId = 1,
                            TotalCost = 80.00m
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 7,
                            ScheduledAt = new DateTime(2026, 6, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            StylistId = 3,
                            TotalCost = 20.00m
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 8,
                            ScheduledAt = new DateTime(2026, 6, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            StylistId = 2,
                            TotalCost = 55.00m
                        });
                });

            modelBuilder.Entity("HillarysHair.Models.AppointmentService", b =>
                {
                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.HasKey("AppointmentId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AppointmentServices");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            AppointmentId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            AppointmentId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            AppointmentId = 2,
                            ServiceId = 2
                        },
                        new
                        {
                            AppointmentId = 3,
                            ServiceId = 3
                        },
                        new
                        {
                            AppointmentId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            AppointmentId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            AppointmentId = 5,
                            ServiceId = 1
                        },
                        new
                        {
                            AppointmentId = 5,
                            ServiceId = 2
                        },
                        new
                        {
                            AppointmentId = 6,
                            ServiceId = 1
                        },
                        new
                        {
                            AppointmentId = 6,
                            ServiceId = 4
                        },
                        new
                        {
                            AppointmentId = 7,
                            ServiceId = 3
                        },
                        new
                        {
                            AppointmentId = 8,
                            ServiceId = 1
                        },
                        new
                        {
                            AppointmentId = 8,
                            ServiceId = 3
                        });
                });

            modelBuilder.Entity("HillarysHair.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "luffy@strawhat.crew",
                            Name = "Monkey D. Luffy",
                            Phone = "(803) 555-0201"
                        },
                        new
                        {
                            Id = 2,
                            Email = "zoro@strawhat.crew",
                            Name = "Roronoa Zoro",
                            Phone = "(803) 555-0202"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sanji@strawhat.crew",
                            Name = "Vinsmoke Sanji",
                            Phone = "(803) 555-0203"
                        },
                        new
                        {
                            Id = 4,
                            Email = "usopp@strawhat.crew",
                            Name = "Usopp",
                            Phone = "(803) 555-0204"
                        },
                        new
                        {
                            Id = 5,
                            Email = "chopper@strawhat.crew",
                            Name = "Tony Tony Chopper",
                            Phone = "(803) 555-0205"
                        },
                        new
                        {
                            Id = 6,
                            Email = "law@heart.pirates",
                            Name = "Trafalgar Law",
                            Phone = "(803) 555-0206"
                        },
                        new
                        {
                            Id = 7,
                            Email = "ace@whitebeard.pirates",
                            Name = "Portgas D. Ace",
                            Phone = "(803) 555-0207"
                        },
                        new
                        {
                            Id = 8,
                            Email = "mihawk@shichibukai.gov",
                            Name = "Dracule Mihawk",
                            Phone = "(803) 555-0208"
                        });
                });

            modelBuilder.Entity("HillarysHair.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Haircut",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Coloring",
                            Price = 75.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Beard Trim",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Deep Conditioning",
                            Price = 45.00m
                        });
                });

            modelBuilder.Entity("HillarysHair.Models.Stylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stylists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "nami@strawhat.crew",
                            IsActive = true,
                            Name = "Nami",
                            Phone = "(803) 555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Email = "robin@strawhat.crew",
                            IsActive = true,
                            Name = "Nico Robin",
                            Phone = "(803) 555-0102"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hancock@kuja.pirates",
                            IsActive = true,
                            Name = "Boa Hancock",
                            Phone = "(803) 555-0103"
                        },
                        new
                        {
                            Id = 4,
                            Email = "perona@thriller.bark",
                            IsActive = false,
                            Name = "Perona",
                            Phone = "(803) 555-0104"
                        });
                });

            modelBuilder.Entity("HillarysHair.Models.Appointment", b =>
                {
                    b.HasOne("HillarysHair.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHair.Models.Stylist", "Stylist")
                        .WithMany("Appointments")
                        .HasForeignKey("StylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Stylist");
                });

            modelBuilder.Entity("HillarysHair.Models.AppointmentService", b =>
                {
                    b.HasOne("HillarysHair.Models.Appointment", "Appointment")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HillarysHair.Models.Service", "Service")
                        .WithMany("AppointmentServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HillarysHair.Models.Appointment", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("HillarysHair.Models.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("HillarysHair.Models.Service", b =>
                {
                    b.Navigation("AppointmentServices");
                });

            modelBuilder.Entity("HillarysHair.Models.Stylist", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
